import uuid
from datetime import datetime

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column


class UUIDMixin:
    """UUID primary key, generated by Postgres (``gen_random_uuid()``)."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, server_default=func.gen_random_uuid()
    )


class TimestampMixin:
    """Row timestamps.

    ``created_at`` is set by the database (``server_default``). ``updated_at`` is
    bumped by SQLAlchemy's ``onupdate`` on ORM flush — a raw SQL ``UPDATE`` would
    bypass it, so add a DB trigger if non-ORM writes are ever introduced.
    """

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
